apiVersion: v1
kind: Pod
metadata:
  name: matrix-pod
spec:
  containers:
  - name: matrix-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: matrix-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: matrix-secret
          key: password

