apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx-deployment:1.19.1
          name: nginx-deployment
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 128Mi
