apiVersion: v1
kind: Pod
metadata:
  labels:
    run: matrix
  name: matrix
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    args: ["sleep", "1800"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
