apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
    - image: nginx
      name: nginx-giropops
      volumeMounts:
        - mountPath: /nginx-giropops
          name: first-emptydir
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 128Mi
          cpu: 1
        requests:
          memory: 64Mi
          cpu: 0.5
      args: ["sleep", "1800"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: first-emptydir
      emptyDir:
        sizeLimit: 256Mi
