apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: my-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.105
    path: "/mnt/nfs"
  storageClassName: matrix
