apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: my-first-pvc
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: matrix
  selector:
    matchLabels:
      storage: nfs

