apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:1.19.2
          name: nginx
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: 0.25
              memory: 128Mi
          livenessProbe: # Onde definimos a nossa probe de vida
            exec: # O tipo exec é utilizado quando queremos executar algo dentro do container.
              command: # Onde iremos definir qual comando iremos executar
                - curl
                - -f
                - http://localhost:80/
            initialDelaySeconds: 10 # O tempo que iremos esperar para executar a primeira vez a probe
            periodSeconds: 10 # De quanto em quanto tempo iremos executar a probe
            timeoutSeconds: 5 # O tempo que iremos esperar para considerar que a probe falhou
            successThreshold: 1 # O número de vezes que a probe precisa passar para considerar que o container está pronto
            failureThreshold: 3 # O número de vezes que a probe precisa falhar para considerar que o container não está pronto
          readinessProbe: # Onde definimos a nossa probe de prontidão
            httpGet: # O tipo de teste que iremos executar, neste caso, iremos executar um teste HTTP
              path: / # O caminho que iremos testar
              port: 80 # A porta que iremos testar
            initialDelaySeconds: 10 # O tempo que iremos esperar para executar a primeira vez a probe
            periodSeconds: 10 # De quanto em quanto tempo iremos executar a probe
            timeoutSeconds: 5 # O tempo que iremos esperar para considerar que a probe falhou
            successThreshold: 1 # O número de vezes que a probe precisa passar para considerar que o container está pronto
            failureThreshold: 3 # O número de vezes que a probe precisa falhar para considerar que o container não está pronto
          startupProbe: # Onde definimos a nossa probe de inicialização
            tcpSocket: # O tipo de teste que iremos executar, neste caso, iremos executar um teste TCP
              port: 80 # A porta que iremos testar
            initialDelaySeconds: 10 # O tempo que iremos esperar para executar a primeira vez a probe
            periodSeconds: 10 # De quanto em quanto tempo iremos executar a probe
            timeoutSeconds: 5 # O tempo que iremos esperar para considerar que a probe falhou
            successThreshold: 1 # O número de vezes que a probe precisa passar para considerar que o container está pronto
            failureThreshold: 3 # O número de vezes que a probe precisa falhar para considerar que o container não está pronto
