apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-girus
    opa: sensacional-juvenal
  name: nginx-girus
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-girus
      opa: sensacional-juvenal
  template:
    metadata:
      labels:
        app: nginx-girus
        opa: sensacional-juvenal
    spec:
      containers:
        - image: nginx:1.16.0
          name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
